// <auto-generated />

#nullable disable

#nullable disable

namespace HaasConnectorAPIs.Migrations;

/// <summary>
/// Defines the <see cref="AppDbContextModelSnapshot" />
/// </summary>
[DbContext(typeof(AppDbContext))]
public class AppDbContextModelSnapshot : ModelSnapshot
{
    /// <summary>
    /// The BuildModel
    /// </summary>
    /// <param name="modelBuilder">The modelBuilder<see cref="ModelBuilder"/></param>
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

        modelBuilder.Entity("HaasConnectorService.Models.HaasDB", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ParamaterName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("time")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("HaasData");
            });
    }
}
